<?php
$hariNama = [1 => 'Senin', 2 => 'Selasa', 3 => 'Rabu', 4 => 'Kamis', 5 => 'Jumat', 6 => 'Sabtu', 7 => 'Minggu'];
$displaySessions = $sesiList ?: [['id' => 0, 'hari' => '', 'jam_mulai' => '', 'jam_selesai' => '', 'tentor_id' => '', 'mata_pelajaran' => '', 'ruangan' => '']];
?>
<div class="flex flex-col gap-5 w-full max-w-3xl mx-auto pb-8">
    <div class="flex items-center gap-3"><a href="/admin/jadwal" class="w-10 h-10 rounded-full bg-white text-gray-700 border border-gray-200 flex items-center justify-center shadow-sm"><span class="material-symbols-outlined">arrow_back</span></a><div><h1 class="text-xl font-bold text-[#1B4332]">Ubah Jadwal Kelas</h1><p class="text-xs text-gray-500">Atur semua sesi dan tentor dalam kelas ini</p></div></div>
    <section class="bg-[#f0efeb] rounded-2xl p-4 border border-[#e2e0d8] shadow-sm"><div class="flex items-start justify-between gap-3"><div><p class="text-[11px] font-semibold tracking-wider text-gray-500 uppercase">Informasi Kelas</p><h2 class="mt-1 text-lg font-extrabold text-[#1B4332]">Kelas <?= e($kelas['nama']) ?></h2><div class="mt-1 flex items-center gap-2"><span class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-[#e8f3ee] text-[#1b4332]">Program: <?= e($kelas['program_nama']) ?></span><span class="text-xs text-gray-500">• <?= e($kelas['jenjang_nama']) ?></span></div></div><span class="px-2 py-1 bg-white rounded-md text-[11px] text-gray-500 border border-gray-200">Terkunci</span></div><p class="text-[11px] text-gray-400 mt-3 pt-2 border-t border-gray-200 italic">Nama kelas dan program ditetapkan dari data kelas induk.</p></section>
    <form action="/admin/kelas/<?= $kelas['id'] ?>/jadwal/update" method="POST" class="flex flex-col gap-4">
        <div class="flex items-center justify-between"><div><h2 class="text-[15px] font-bold text-[#1B4332]">Daftar Sesi & Tentor</h2><p class="text-xs text-gray-500">Tambah, ubah, atau hapus sesi kelas.</p></div><span class="text-xs font-semibold text-[#1B4332] bg-[#e8f3ee] px-2.5 py-1 rounded-full"><span id="session-count"><?= count($sesiList) ?></span> Sesi / Minggu</span></div>
        <div id="schedule-list" class="space-y-3">
            <?php foreach ($displaySessions as $index => $sesi): ?>
                <div data-session-card class="bg-white rounded-2xl p-4 border border-gray-200 shadow-sm"><div class="flex items-center justify-between mb-3 pb-2 border-b border-gray-100"><div class="flex items-center gap-2"><span class="session-number w-6 h-6 rounded-full bg-[#1B4332] text-white flex items-center justify-center text-xs font-bold"><?= $index + 1 ?></span><strong class="text-xs text-[#1B4332]">Sesi <?= $index + 1 ?></strong></div><button type="button" data-remove-session class="text-xs text-red-500 flex items-center gap-1"><span class="material-symbols-outlined text-[16px]">delete</span> Hapus</button></div>
                    <input type="hidden" name="sesi[<?= $index ?>][id]" value="<?= e($sesi['id'] ?? 0) ?>">
                    <div class="flex items-center justify-between gap-2 mb-3"><strong class="text-sm text-[#1B4332]"><?= !empty($sesi['hari']) ? $hariNama[(int) $sesi['hari']] : 'Sesi baru' ?> <span class="font-normal text-gray-500">| <?= !empty($sesi['jam_mulai']) ? substr($sesi['jam_mulai'], 0, 5) . ' - ' . substr($sesi['jam_selesai'], 0, 5) . ' WIB' : 'atur waktu belajar' ?></span></strong><span class="text-[11px] px-2 py-0.5 rounded bg-[#faf9f6] text-gray-500 border border-gray-200"><?= e($sesi['mata_pelajaran'] ?? 'Mata pelajaran') ?></span></div>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label class="block text-[11px] font-semibold text-gray-600 mb-1">Hari</label><select name="sesi[<?= $index ?>][hari]" required class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"><option value="">Pilih Hari</option><?php foreach ($hariNama as $day => $name): ?><option value="<?= $day ?>" <?= ((int) ($sesi['hari'] ?? 0) === $day) ? 'selected' : '' ?>><?= $name ?></option><?php endforeach; ?></select></div><div><label class="block text-[11px] font-semibold text-gray-600 mb-1">Mata Pelajaran</label><input name="sesi[<?= $index ?>][mata_pelajaran]" value="<?= e($sesi['mata_pelajaran'] ?? '') ?>" class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"></div></div>
                    <div class="grid grid-cols-2 gap-3 mt-3"><div><label class="block text-[11px] font-semibold text-gray-600 mb-1">Jam Mulai</label><input type="time" name="sesi[<?= $index ?>][jam_mulai]" value="<?= e($sesi['jam_mulai'] ?? '') ?>" required class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"></div><div><label class="block text-[11px] font-semibold text-gray-600 mb-1">Jam Selesai</label><input type="time" name="sesi[<?= $index ?>][jam_selesai]" value="<?= e($sesi['jam_selesai'] ?? '') ?>" required class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"></div></div>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-3 mt-3"><div><label class="block text-[11px] font-semibold text-gray-600 mb-1">Tentor</label><select name="sesi[<?= $index ?>][tentor_id]" class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"><option value="">Belum Ditugaskan</option><?php foreach ($tentorList as $t): ?><option value="<?= $t['id'] ?>" <?= ((int) ($sesi['tentor_id'] ?? 0) === (int) $t['id']) ? 'selected' : '' ?>><?= e($t['nama_lengkap']) ?></option><?php endforeach; ?></select></div><div><label class="block text-[11px] font-semibold text-gray-600 mb-1">Ruangan</label><input name="sesi[<?= $index ?>][ruangan]" value="<?= e($sesi['ruangan'] ?? '') ?>" class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"></div></div>
                    <?php if (isset($errors['sesi_' . $index])): ?><p class="text-xs text-red-600 mt-2"><?= e($errors['sesi_' . $index]) ?></p><?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
        <button type="button" id="add-schedule" class="w-full py-3 rounded-xl border-2 border-dashed border-[#1B4332] text-[#1B4332] font-bold text-xs bg-white"><span class="material-symbols-outlined text-[17px] align-middle">add_circle</span> Tambah Sesi Hari Lain</button>
        <div class="flex gap-3 pt-2"><a href="/admin/jadwal" class="flex-1 py-3 rounded-xl border-2 border-red-500 text-red-600 text-sm font-bold text-center">Batal</a><button class="flex-1 py-3 rounded-xl bg-[#1B4332] text-white text-sm font-bold">Simpan Perubahan</button></div>
    </form>
</div>
<script>
const list = document.getElementById('schedule-list'); const count = document.getElementById('session-count'); const days = <?= json_encode($hariNama) ?>; const tutors = <?= json_encode(array_map(fn ($t) => ['id' => $t['id'], 'name' => $t['nama_lengkap']], $tentorList)) ?>;
function renumber() { list.querySelectorAll('[data-session-card]').forEach((card, i) => { card.querySelector('.session-number').textContent = i + 1; card.querySelector('strong').textContent = 'Sesi ' + (i + 1); card.querySelectorAll('[name]').forEach(el => el.name = el.name.replace(/sesi\[\d+\]/, 'sesi[' + i + ']')); }); count.textContent = list.querySelectorAll('[data-session-card]').length; }
document.getElementById('add-schedule').addEventListener('click', () => { const i = list.querySelectorAll('[data-session-card]').length; const dayOptions = Object.entries(days).map(([id, name]) => `<option value="${id}">${name}</option>`).join(''); const tutorOptions = tutors.map(t => `<option value="${t.id}">${t.name}</option>`).join(''); const card = document.createElement('div'); card.setAttribute('data-session-card', ''); card.className = 'bg-white rounded-2xl p-4 border border-gray-200 shadow-sm'; card.innerHTML = `<div class="flex items-center justify-between mb-3 pb-2 border-b border-gray-100"><div class="flex items-center gap-2"><span class="session-number w-6 h-6 rounded-full bg-[#1B4332] text-white flex items-center justify-center text-xs font-bold">${i + 1}</span><strong class="text-xs text-[#1B4332]">Sesi ${i + 1}</strong></div><button type="button" data-remove-session class="text-xs text-red-500">Hapus</button></div><input type="hidden" name="sesi[${i}][id]" value="0"><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><select required name="sesi[${i}][hari]" class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"><option value="">Pilih Hari</option>${dayOptions}</select><input name="sesi[${i}][mata_pelajaran]" placeholder="Mata Pelajaran" class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"></div><div class="grid grid-cols-2 gap-3 mt-3"><input required type="time" name="sesi[${i}][jam_mulai]" class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"><input required type="time" name="sesi[${i}][jam_selesai]" class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"></div><div class="grid grid-cols-1 md:grid-cols-2 gap-3 mt-3"><select name="sesi[${i}][tentor_id]" class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"><option value="">Belum Ditugaskan</option>${tutorOptions}</select><input name="sesi[${i}][ruangan]" placeholder="Ruangan" class="w-full px-3 py-2.5 rounded-xl border border-gray-200 bg-[#FAF9F6] text-sm"></div>`; list.appendChild(card); renumber(); });
list.addEventListener('click', e => { if (e.target.closest('[data-remove-session]')) { e.target.closest('[data-session-card]').remove(); renumber(); } });
</script>
